### PR TITLE
Final TomoX & TomoZ 

### LINKED ISSUE #69: Port Lending Service from legacy Viction client
## Description

Port the Lending Service from the original Viction client (tomochain-v1) to vic-geth.

## Status

In progress — PR #62.

### LINKED ISSUE #78: Bad Block #20,582,101: Missing TomoX TradingStateDB implementation
## Description

Sync fails at block **20,582,101** due to missing TomoX feature implementation.

## Error

```
########## BAD BLOCK #########
Number: 20582101
Hash: 0xabe0ba93dbf48b3bc2bf21c46f6e444cbd9fd98ec398ef2aeb81a71eb05519cf
Error: TomoX: failed to open TradingStateDB at block 20582101: missing trie node 2d1ffaa87ce729855d1a7f153393ff81fe52bb5ad49fe5c716da68df081a0944 (path )
```

## Root Cause

Block 20,582,101 falls after the `TIPTomoX` fork (enabled at block 20,581,700). The TomoX (DEX) feature code has not been ported to vic-geth yet, so the `TradingStateDB` trie is missing entirely.

## Resolution

Requires porting the TomoX feature from the legacy Viction client to vic-geth.

### PR DESCRIPTION
**Pull request by 0xendale**
## Summary

This PR completes the full port of TomoX (on-chain DEX) and TomoZ (on-chain lending) from the legacy monolithic client into the vic-geth hook architecture. The node can now sync all pre-Atlas blocks containing TomoX/TomoZ state without state root mismatches.

---

### Trie persistence — deferred commit strategy (`blockchain_viction.go`, `state_processor.go`)

The previous code had no mechanism to flush trading/lending trie nodes to LevelDB. Dirty nodes accumulated in `trie.Database.dirties` and were eventually GC'd without ever being written — meaning any trie opened from a committed root would be missing nodes on the next block.

`commitVictionState` (called from `insertChain` after `writeBlockWithState`) mirrors the deferred-commit strategy used for the main EVM trie:

- **Full-node path**: commit the current block's root to LevelDB immediately (not deferred) to avoid the "nodes=0" bug where `GetTradingStateRoot` returns `EmptyRoot` for blocks with no 0x92 tx, causing dirty nodes to accumulate without a committed root to anchor them. GC is still deferred by `TriesInMemory` blocks for reorg safety.
- **Archive path**: flush every block directly, no GC queue needed.
- **Shutdown**: `stopViction` (called from `BlockChain.Stop`) flushes the tail of both queues so no roots are lost on clean exit.

`StateProcessor` gains two `prque.Prque` fields (`tradingTriegc`, `lendingTriegc`) to hold the deferred root queues.

### Liquidation fix — shared trie objects (`state_processor_viction.go`)

Previously `beforeProcessViction` in `blockchain.go` opened its own private trading/lending trie, ran `ProcessLiquidationData` (writing AutoTopUp changes), then discarded both objects. `beforeProcess` in `state_processor_viction.go` then opened a second fresh trie from the same parent — with none of the AutoTopUp writes — committed that stale root, and produced a mismatch.

The fix moves liquidation entirely into `beforeProcess`, where it runs on the same trie objects that the transaction loop and `afterProcess` share. `beforeProcessViction` in `blockchain.go` is now a no-op stub.

### Commit-before-hash ordering fix (`state_processor_viction.go` — `afterProcess`)

`IntermediateRoot()` (previously used for root verification) collapses dirty nodes into hash nodes in-place. A subsequent `trie.Commit()` on a fully-hashed trie finds no dirty nodes and writes nothing to `trie.Database.dirties`. The fix calls `tradingStateDB.Commit()` / `lendingStateDB.Commit()` first to stage dirty nodes into the database, then verifies the returned root against the 0x92 system transaction. The committed roots are stored in `victionProcessorState` for `commitVictionState` to flush to LevelDB.

### TomoX and TomoZ trie opening unified (`beforeProcess`)

The two separate trie-open blocks (one gated on `IsTIPTomoX`, one on `IsTIPTomoXLending`) are merged into a single block gated on `IsTomoXEnabled` (the TIPTomoX–Atlas window). Both tries now open from the same parent fetch and author resolution.

### LendingEngine interface moved (`lending_engine.go` deleted, `state_processor_viction.go`)

`LendingEngine` was defined in a standalone `core/lending_engine.go`. It is now defined alongside `TradingEngine` in `state_processor_viction.go` (the correct location per hook-architecture rules). The file is deleted.

`TradingEngine` gains `GetTradingStateRoot` and `GetStateCache`; `LendingEngine` gains `GetStateCache`. Both are required for the trie-persistence machinery.

### Transaction type helpers (`core/types/transaction_viction.go`)

`IsTomoXApplyTransaction` and the hardcoded-address `IsTradingTransaction` are replaced with config-driven `IsTradingTransaction`, `IsLendingTransaction`, and `IsLendingFinalizedTradeTransaction` methods that read addresses from `ChainConfig.Viction`. This eliminates hardcoded addresses and makes system-tx detection consistent with the config.

`applyVictionTransaction` now decodes each batch once (before dispatching) so `applyTomoXTx` and `applyLendingTx` receive a pre-decoded batch rather than raw bytes.

### `header.Coinbase` → recovered author (`applyTomoXTx`, `applyLendingTx`)

PoSV blocks set `header.Coinbase` to zero. The correct masternode address for fee accounting is the block author recovered from the header signature via `engine.Author()`. Both apply functions now use this.

### `TryGetAllLeftKeyAndValue` signature fix (`tradingstate/tomox_trie.go`, `lendingstate/tomox_trie.go`)

The previous implementation converted the `[]byte` limit argument to an integer count, silently changing semantics. The underlying `trie.Trie.TryGetAllLeftKeyAndValue` was updated to accept a `[]byte` key upper-bound directly; both trie wrappers now pass the argument through unchanged.

### Relayer validation address fix (`tradingstate/orderitem.go`)

`IsValidRelayer` was reading the relayer deposit balance from `TomoNativeAddress` (0x01). It now reads from `RelayerRegistrationSMC` (the actual relayer registry contract), which is also corrected from the wrong placeholder to `0x16c63b79f9C8784168103C0b74E6A59EC2de4a02`.

### Fee constants corrected (`tradingstate/common.go`)

`RelayerLockedFund`, `RelayerFee`, `RelayerCancelFee`, and `TomoXBaseCancelFee` were set to placeholder values. Corrected to match the deployed contract values.

### Debug logging added

`DoSettleBalance` and `ProcessCancelOrder` in both `tomox` and `tomoxlending` now log the coinbase, masternode owner, and fee at `Debug` level to aid future tracing.

### Receipt logs populated

`applyTomoXTx` and `applyLendingTx` now call `statedb.GetLogs(tx.Hash())` to populate `receipt.Logs` before computing the bloom filter, matching standard tx processing.

### `IsTomoXEnabled` / `IsTomoXLendingEnabled` added (`params/config.go`)

Two helpers encapsulate the TIPTomoX–Atlas window check that was previously duplicated inline.

---

## Scope

Sync path only. Block production is not changed. TomoX and TomoZ are disabled at Atlas (`IsTomoXEnabled` returns false), matching the deployed network behaviour.

### CODE REVIEW

File: core/state_processor.go [hunk 1]
```diff
@@ -45,14 +46,21 @@ type StateProcessor struct {
 	// lending orders and liquidations during sync. Set via SetLendingEngine(). Nil when
 	// TomoZ lending is not needed.
 	lendingEngine LendingEngine
+
+	// Deferred trie GC fields for TomoX/TomoZ (full-node path).
+	// These are managed entirely by blockchain_viction.go / commitVictionState.
+	tradingTriegc *prque.Prque // deferred GC queue for TomoX trading trie roots
```
Comment (imduchuyyy) [inline core/state_processor.go:52]: can you explain what is this

Comment (0xendale) [reply core/state_processor.go:52]: This is the same pattern Geth uses for the main EVM state trie. It's a priority queue that tracks which trie roots can be safely deleted from memory.

Every block, `TradingStateDB.Commit()` stages dirty trie nodes into an in-memory cache (`trie.Database.dirties`). Those nodes must eventually be:
1. Written to `LevelDB` (persisted), then
2. Dereferenced (freed from the in-memory cache)

If you write to `LevelDB` and immediately dereference on every single block, you get excessive write amplification. Geth's solution (which we mirror here) is to defer the dereference by TriesInMemory (128) blocks , giving a 128-block reorg window where old roots are still in memory. The priority queue holds `(root, blockNumber)` pairs so we know when each root is old enough to dereference.

`TomoX` (trading) and `TomoZ` (lending) are separate `LevelDB` databases with separate `trie.Database` instances. Each needs its own GC queue because their roots are independent , a lending root and a trading root committed at the same block are stored in different backing stores.

In short: it's the standard Geth deferred-trie-GC pattern, applied to the `TomoX` and `TomoZ` tries so they don't leak memory or cause excessive disk writes.

**Review by imduchuyyy — APPROVED** [review]
LGTM
