### PR TITLE
Fix VRC25 process 

### LINKED ISSUE #72: Bad block at 9,364,509: state root mismatch (non-checkpoint block)
## Description

Node hits a bad block at **block 9,364,509** with an invalid merkle root error during sync. This is **not a checkpoint block** (9364509 % 900 = 409), so it is not related to epoch reward distribution.

The state root computed locally does not match the expected remote state root.

**Status:** Under investigation — root cause unknown.

## Error Log

```
######### BAD BLOCK #########
Chain config: {ChainID: 88 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Petersburg: 30915660 Istanbul: 30915660, Muir Glacier: <nil>, YOLO v2: <nil>, TIP2019: 1050000, TIPSigning: 3000000, TIPRandomize: 3464000, TIPBlacklist: 9349100, TIPTRC21Fee: 13523400, TIPFixSignerCheck: 14458500, TIPTomoX: <nil>, TIPTomoXLending: <nil>, TIPTomoXCancelFee: <nil>, Saigon: 86158494, Atlas: 97705094, Engine: posv}
Number: 9364509
Hash: 0xcdcc0faa434bcc41903d42a7bfe47850b551b1c55d74bb9c1305128891b7fe29
   0: cumulative: 42527 gas: 42527 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x654d0ae8d3fbdd8382c1a5bfd2e787e16d584b43c1c04ebf114e026ca49e4d60 logs: [] bloom: 00...00 state:
Error: invalid merkle root (remote: 14e51ed46326f6cc218198d61d1cb4e264674ce9155e2df3b8cdb80a9a392da5 local: 4a34f4a3f0844afa984b5f21a23203efe4ad1b0eb9fffad38b4c2c22c1f346d1)
##############################
```

## Context

- **Block number:** 9,364,509
- **Block hash:** `0xcdcc0faa434bcc41903d42a7bfe47850b551b1c55d74bb9c1305128891b7fe29`
- **Expected state root (remote):** `14e51ed46326f6cc218198d61d1cb4e264674ce9155e2df3b8cdb80a9a392da5`
- **Computed state root (local):** `4a34f4a3f0844afa984b5f21a23203efe4ad1b0eb9fffad38b4c2c22c1f346d1`
- **Checkpoint block:** No (9364509 % 900 = 409)
- **Transaction count:** 1
- **Transaction:** `0x654d0ae8d3fbdd8382c1a5bfd2e787e16d584b43c1c04ebf114e026ca49e4d60` (gas: 42527, status: success)
- **Network:** Viction mainnet (chain ID 88)

## Notable Fork Context

Block 9,364,509 is **just after TIPBlacklist activation** (block 9,349,100). The TIPBlacklist fork activated ~15,409 blocks earlier. This may be relevant if the fork introduces state changes that are handled differently.

## Investigation Notes
 
- The block contains a single transaction that executed successfully (status: 1).
- Possible areas to investigate:
  - State transition logic changes introduced by TIPBlacklist fork
  - Transaction sponsorgas (VRC25 Transaction)
  - Any Finalize-time state modifications at non-checkpoint blocks

### PR DESCRIPTION
**Pull request by endale98**
sumary : `vic-geth` produced a state root mismatch against `victionchain` on blocks via mismatch involving VRC25-sponsored transactions (gas paid via token fee instead of native VIC).

### Bug 1 — Wrong payer / unnetted SubBalance during buyGas.
Fix :
`core/state_transition.go` — `buyGas`
Added pre-Atlas sponsored tx early return to skip balance check and `SubBalance`:
```go
// Pre-Atlas sponsored tx: payer = VRC25Contract but victionchain does not
// SubBalance from the issuer contract in the pre-Atlas path.
if st.isVRC25Transaction() && !st.evm.ChainConfig().IsAtlas(st.evm.Context.BlockNumber) {
    return nil
}
```
Also modifier `VRC25BuyGas` to match the check .
### Bug 2 — Missing end-of-block fee flush.
fix — `core/state_processor_viction.go` — `feeBalance`/`feeUpdated`/`totalFee` fields in `victionProcessorState`; snapshotted in `beforeProcess`; decremented per tx in `afterApplyTransaction`; flushed via `vrc25.UpdateFeeCapacity` in `afterProcess`.
### Bug 3 — Atlas eligibility off-by-one : 
fix — `core/state_transition_viction.go:vrc25BuyGas` — changed to `<= 0`.
### Bug 4 — Failed-tx minimum fee not applied pre-TIPTRC21Fee.
fix — `core/state_processor_viction.go:afterApplyTransaction` — era guard removed; fires inside the `feeBalance` eligibility check for any pre-Atlas failed sponsored tx.

### Bug 5 - Wrong gas price constant:
Fix:  `afterApplyTransaction `change to use vicCfg.VRC25GasPrice .

### CODE REVIEW

File: core/state_transition.go [hunk 1]
```diff
@@ -181,16 +181,20 @@ func (st *StateTransition) buyGas() error {
...
-	if have, want := st.state.GetBalance(st.payer), mgval; have.Cmp(want) < 0 {
-		return fmt.Errorf("%w: address %v have %v want %v", ErrInsufficientFunds, st.payer.Hex(), have, want)
-	}
 	if err := st.gp.SubGas(st.msg.Gas()); err != nil {
 		return err
 	}
 	st.gas += st.msg.Gas()
 
 	st.initialGas = st.msg.Gas()
+	// Pre-Atlas sponsored tx
```
Comment (imduchuyyy) [inline core/state_transition.go:190]: why you move this below of gp.SubGas statement?

Comment (endale98) [reply core/state_transition.go:190]: viction legacy code check sponsor gas via `if balanceTokenFee == nil` via `subtractBalance` at the end of this func, so i think it valid

**Review by imduchuyyy — APPROVED** [review]
This PR can be merged, but need to revalidate in the future for post-atlas execution logic.
